version: '3.8'

services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=airport_advisor_system_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=airport_advisor_system_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
