
services:
  db:
      image: mysql:8.0
      container_name: my_mysql_db
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=airport_advisor_system_db
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$password"]
        interval: 10s
        timeout: 5s
        retries: 5
  app:
    build: .
    container_name: my_node_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=my_mysql_db
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=password
      - DB_NAME=airport_advisor_system_db
    depends_on:
        db:
          condition: service_healthy


volumes:
  db_data:
